<?php

namespace MCris112\Billable\Facades;

use Illuminate\Support\Facades\Facade;

class Orderable extends Facade
{

    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
